http_listen_addr: :8081
introspection_addr: :8088
log_level: debug
indexer:
  connstring: host=bastion.nuc.lab port=5433 dbname=clair user=clair password=pass sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: host=bastion.nuc.lab port=5433 dbname=clair user=clair password=pass sslmode=disable
  max_conn_pool: 100
  migrations: true
  indexer_addr: clair-indexer
notifier:
  connstring: host=bastion.nuc.lab port=5433 dbname=clair user=clair password=pass sslmode=disable
  delivery_interval: 1m
  poll_interval: 5m
  migrations: true
auth:
  psk:
    key: "NmEwOGU5NDBqODU5"
    iss: ["quay","clairctl"]
# tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent:
      endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
